### ISSUE TITLE
fail to open fasta file

### ISSUE THREAD

**Issue by hafizmtalha** [katholt/genotyphi#24]
I am facing this issue while running genotyphi. File path is correct and it is a fasta file

> [fai_build] fail to open the FASTA file temp_reference.fasta
Could not build fai index temp_reference.fasta.fai
Traceback (most recent call last):
  File "genotyphi.py", line 472, in <module>
    main()
  File "genotyphi.py", line 339, in main
    run_command(['samtools', 'faidx', 'temp_reference.fasta'])  # index fasta file
  File "genotyphi.py", line 300, in run_command

**Comment by katholt** [comment]
looks like you don't have write permissions in the directory where the fasta file is stored, permissions are required to index the file for use with samtools
