### ISSUE TITLE
Plans for BioConda release?

### ISSUE THREAD

**Issue by rpetit3** [katholt/genotyphi#29]
Hello! 

Do you have plans for a Bioconda release? If not I would like create a recipe, but would need a versioned release  to get started.

Thanks!
Robert

**Comment by zadyson** [comment]
Dear Robert,

Thanks for the message and for your interest - this sounds great!  I've just created a versioned release for you (v1.6), please do let me know if any issues arise or if you need anything else to get started.

Thanks and best wishes,

Zoe.

**Comment by rpetit3** [comment]
Great! Thank you!

Quick questions on dependencies:

Python 2.7.5+ - Does Python3 work ok? 

Other than Python are only SAMtools and BCFtools the other dependencies?

**Comment by zadyson** [comment]
Hi Robert,

Thanks for the messages!

At the moment we are still using python 2 for GenoTyphi, and you are correct in that the only (non-python) dependencies are SAMtools and BCFtools.  In terms of execution, I think either genotyphi.py or both would be best, thanks for checking!

Thanks and best wishes,

Zoe.

**Comment by rpetit3** [comment]
Thank you! 

Last thing, you'll need to attach a license to the repo (https://choosealicense.com/). Then everything should be all set to make a recipe

**Comment by zadyson** [comment]
Taken care of, thanks again Robert!

**Comment by rpetit3** [comment]
Almost there! See: https://github.com/bioconda/bioconda-recipes/pull/25674

I'll need you to delete the current release and recreate it so that the LICENSE file is included.
```
ValueError: License file given in about/license_file (/opt/recipe/LICENSE) does not exist in source root dir or in recipe root dir (with meta.yaml)
```

**Comment by zadyson** [comment]
Thanks Robert, I've re-released as v1.7.1 with the updated licence, hope this helps!

Best wishes,

Zoe.

**Comment by rpetit3** [comment]
It did! PR submitted and everything passed: https://github.com/bioconda/bioconda-recipes/pull/25674 Now someone will need to approve then you are all set. New releases will be automatically recognized and built on Bioconda.

Heads up the version number in `genotyphi.py` is still 1.7.0.

**Comment by zadyson** [comment]
Wonderful, thanks for all your help Robert!

Best wishes,

Zoe.
