### ISSUE TITLE
Code seem broken

### ISSUE THREAD

**Issue by emmannaemeka** [katholt/genotyphi#32]
Hello,
Please am trying to run the script using the commandline

 python genotyphi.py --mode vcf_parsnp --vcf /Users/emmannadi/Desktop/bioinformatics_tools/Harvest-OSX64-v1.1.2/Sal.vcf  --ref_id AL513382.1 --output genotypes_parsnptest.txt

It returned this error
File "genotyphi.py", line 185
    if level ==	5:
                 ^

Please can you help?

**Comment by zadyson** [comment]
Hello,

Thanks for reporting the issue to us.  I've had a look at the code and I'm sorry but I can't replicate the error with parsnp input on our end.  It might be good to double check the version of python you are using to run the code to see if that helps.  We recommend using python 2, more specifically version 2.7 under which our testing has been conducted (please see below example).

```
[zdyson@m3-login1 ~]$ python --version
Python 2.7.12

```

I hope this helps, if it doesn't please feel free to share your input file so we can help test this for you.

Thanks and best wishes,

Zoe.

**Comment by emmannaemeka** [comment]
Thanks Zoe,
Please If I can get a mail to send the input file to I will be glad to. 

I just ran the commandline
python2.7 genotyphi.py --mode vcf_parsnp --vcf /Users/emmannadi/Desktop/bioinformatics_tools/Harvest-OSX64-v1.1.2/Sal.vcf  --ref_id AL513382.1 --output genotypes_parsnptest.txtgr

and got 

Traceback (most recent call last):
  File "genotyphi.py", line 521, in <module>
    main()
  File "genotyphi.py", line 513, in main
    output_file.write(strains[strain] + '\tNo SNPs encountered against expected reference. Wrong reference or no SNP calls?\n')
UnboundLocalError: local variable 'strain' referenced before assignment

Thanks

**Comment by zadyson** [comment]
Thanks for the response @emmannaemeka .  Sorry to hear that specifying the python version hasn't helped.  I've received your email with the file and will take a look.

Best wishes,

Zoe.

**Comment by zadyson** [comment]
Hello @emmannaemeka ,

Thanks again for the email, I've had a look at your data and the reference id in your vcf files is NC_003198.1 for the version of the CT18 reference sequence you have used, so for your input data the --ref_id will be NC_003198.1.  If you ever need to check this in the future you can do so by  opening your vcf files in a text editor and looking at the id listed under the #CHROM column.  

So, the command that will work for your input is:

` python genotyphi.py --mode vcf_parsnp --vcf ./user_input/Sal.vcf --ref_id NC_003198.1`

I'll email you the output files from the run I did with your data as well in case this helps.  I'll also update our documentation so this is clearer for others in the future.

I hope this helps!

Best wishes,

Zoe.
